language: python
install:
    - pip install coveralls

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"

script:
    - nosetests -s

after_success:
    - coverage run --source=terminal setup.py -q nosetests
    - coveralls

notifications:
    email: false
